/**
 * generated by Xtext 2.21.0
 */
package org.xtext.system.dependency.dependency;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.system.dependency.dependency.DependencyFactory
 * @model kind="package"
 * @generated
 */
public interface DependencyPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dependency";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/system/dependency/Dependency";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dependency";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DependencyPackage eINSTANCE = org.xtext.system.dependency.dependency.impl.DependencyPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.SystemDependencyObjectsImpl <em>System Dependency Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.SystemDependencyObjectsImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getSystemDependencyObjects()
   * @generated
   */
  int SYSTEM_DEPENDENCY_OBJECTS = 0;

  /**
   * The feature id for the '<em><b>Username</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS__USERNAME = 0;

  /**
   * The feature id for the '<em><b>Userimport</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS__USERIMPORT = 1;

  /**
   * The feature id for the '<em><b>At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS__AT = 2;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS__DEPENDENCIES = 3;

  /**
   * The feature id for the '<em><b>Guis</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS__GUIS = 4;

  /**
   * The number of structural features of the '<em>System Dependency Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEPENDENCY_OBJECTS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.UserNameImpl <em>User Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.UserNameImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getUserName()
   * @generated
   */
  int USER_NAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>User Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.UserImportImpl <em>User Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.UserImportImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getUserImport()
   * @generated
   */
  int USER_IMPORT = 2;

  /**
   * The feature id for the '<em><b>Environment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT__ENVIRONMENT = 0;

  /**
   * The feature id for the '<em><b>Boxpath</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT__BOXPATH = 1;

  /**
   * The number of structural features of the '<em>User Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.AtImpl <em>At</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.AtImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getAt()
   * @generated
   */
  int AT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT__NAME = 0;

  /**
   * The number of structural features of the '<em>At</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.DependencyImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__NAME = 0;

  /**
   * The feature id for the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__FN = 1;

  /**
   * The feature id for the '<em><b>Fp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__FP = 2;

  /**
   * The feature id for the '<em><b>O</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__O = 3;

  /**
   * The feature id for the '<em><b>Tn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__TN = 4;

  /**
   * The feature id for the '<em><b>Tp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__TP = 5;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.system.dependency.dependency.impl.GUIImpl <em>GUI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.system.dependency.dependency.impl.GUIImpl
   * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getGUI()
   * @generated
   */
  int GUI = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__Y = 2;

  /**
   * The number of structural features of the '<em>GUI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects <em>System Dependency Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Dependency Objects</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects
   * @generated
   */
  EClass getSystemDependencyObjects();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects#getUsername <em>Username</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Username</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects#getUsername()
   * @see #getSystemDependencyObjects()
   * @generated
   */
  EReference getSystemDependencyObjects_Username();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects#getUserimport <em>Userimport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Userimport</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects#getUserimport()
   * @see #getSystemDependencyObjects()
   * @generated
   */
  EReference getSystemDependencyObjects_Userimport();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects#getAt <em>At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>At</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects#getAt()
   * @see #getSystemDependencyObjects()
   * @generated
   */
  EReference getSystemDependencyObjects_At();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects#getDependencies()
   * @see #getSystemDependencyObjects()
   * @generated
   */
  EReference getSystemDependencyObjects_Dependencies();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.system.dependency.dependency.SystemDependencyObjects#getGuis <em>Guis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Guis</em>'.
   * @see org.xtext.system.dependency.dependency.SystemDependencyObjects#getGuis()
   * @see #getSystemDependencyObjects()
   * @generated
   */
  EReference getSystemDependencyObjects_Guis();

  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.UserName <em>User Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Name</em>'.
   * @see org.xtext.system.dependency.dependency.UserName
   * @generated
   */
  EClass getUserName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.UserName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.system.dependency.dependency.UserName#getName()
   * @see #getUserName()
   * @generated
   */
  EAttribute getUserName_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.UserImport <em>User Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Import</em>'.
   * @see org.xtext.system.dependency.dependency.UserImport
   * @generated
   */
  EClass getUserImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.UserImport#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Environment</em>'.
   * @see org.xtext.system.dependency.dependency.UserImport#getEnvironment()
   * @see #getUserImport()
   * @generated
   */
  EAttribute getUserImport_Environment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.UserImport#getBoxpath <em>Boxpath</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boxpath</em>'.
   * @see org.xtext.system.dependency.dependency.UserImport#getBoxpath()
   * @see #getUserImport()
   * @generated
   */
  EAttribute getUserImport_Boxpath();

  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.At <em>At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>At</em>'.
   * @see org.xtext.system.dependency.dependency.At
   * @generated
   */
  EClass getAt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.At#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.system.dependency.dependency.At#getName()
   * @see #getAt()
   * @generated
   */
  EAttribute getAt_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getName()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getFn <em>Fn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fn</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getFn()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Fn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getFp <em>Fp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fp</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getFp()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Fp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getO <em>O</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>O</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getO()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_O();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getTn <em>Tn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tn</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getTn()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Tn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.Dependency#getTp <em>Tp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tp</em>'.
   * @see org.xtext.system.dependency.dependency.Dependency#getTp()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Tp();

  /**
   * Returns the meta object for class '{@link org.xtext.system.dependency.dependency.GUI <em>GUI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GUI</em>'.
   * @see org.xtext.system.dependency.dependency.GUI
   * @generated
   */
  EClass getGUI();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.GUI#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.system.dependency.dependency.GUI#getName()
   * @see #getGUI()
   * @generated
   */
  EAttribute getGUI_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.GUI#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.system.dependency.dependency.GUI#getX()
   * @see #getGUI()
   * @generated
   */
  EAttribute getGUI_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.system.dependency.dependency.GUI#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.system.dependency.dependency.GUI#getY()
   * @see #getGUI()
   * @generated
   */
  EAttribute getGUI_Y();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DependencyFactory getDependencyFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.SystemDependencyObjectsImpl <em>System Dependency Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.SystemDependencyObjectsImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getSystemDependencyObjects()
     * @generated
     */
    EClass SYSTEM_DEPENDENCY_OBJECTS = eINSTANCE.getSystemDependencyObjects();

    /**
     * The meta object literal for the '<em><b>Username</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEPENDENCY_OBJECTS__USERNAME = eINSTANCE.getSystemDependencyObjects_Username();

    /**
     * The meta object literal for the '<em><b>Userimport</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEPENDENCY_OBJECTS__USERIMPORT = eINSTANCE.getSystemDependencyObjects_Userimport();

    /**
     * The meta object literal for the '<em><b>At</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEPENDENCY_OBJECTS__AT = eINSTANCE.getSystemDependencyObjects_At();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEPENDENCY_OBJECTS__DEPENDENCIES = eINSTANCE.getSystemDependencyObjects_Dependencies();

    /**
     * The meta object literal for the '<em><b>Guis</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEPENDENCY_OBJECTS__GUIS = eINSTANCE.getSystemDependencyObjects_Guis();

    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.UserNameImpl <em>User Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.UserNameImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getUserName()
     * @generated
     */
    EClass USER_NAME = eINSTANCE.getUserName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_NAME__NAME = eINSTANCE.getUserName_Name();

    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.UserImportImpl <em>User Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.UserImportImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getUserImport()
     * @generated
     */
    EClass USER_IMPORT = eINSTANCE.getUserImport();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_IMPORT__ENVIRONMENT = eINSTANCE.getUserImport_Environment();

    /**
     * The meta object literal for the '<em><b>Boxpath</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_IMPORT__BOXPATH = eINSTANCE.getUserImport_Boxpath();

    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.AtImpl <em>At</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.AtImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getAt()
     * @generated
     */
    EClass AT = eINSTANCE.getAt();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AT__NAME = eINSTANCE.getAt_Name();

    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.DependencyImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__NAME = eINSTANCE.getDependency_Name();

    /**
     * The meta object literal for the '<em><b>Fn</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__FN = eINSTANCE.getDependency_Fn();

    /**
     * The meta object literal for the '<em><b>Fp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__FP = eINSTANCE.getDependency_Fp();

    /**
     * The meta object literal for the '<em><b>O</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__O = eINSTANCE.getDependency_O();

    /**
     * The meta object literal for the '<em><b>Tn</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__TN = eINSTANCE.getDependency_Tn();

    /**
     * The meta object literal for the '<em><b>Tp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__TP = eINSTANCE.getDependency_Tp();

    /**
     * The meta object literal for the '{@link org.xtext.system.dependency.dependency.impl.GUIImpl <em>GUI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.system.dependency.dependency.impl.GUIImpl
     * @see org.xtext.system.dependency.dependency.impl.DependencyPackageImpl#getGUI()
     * @generated
     */
    EClass GUI = eINSTANCE.getGUI();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUI__NAME = eINSTANCE.getGUI_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUI__X = eINSTANCE.getGUI_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUI__Y = eINSTANCE.getGUI_Y();

  }

} //DependencyPackage
