/**
 * generated by Xtext 2.23.0
 */
package org.xtext.system.dependency.dependency;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getFn <em>Fn</em>}</li>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getFp <em>Fp</em>}</li>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getO <em>O</em>}</li>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getTn <em>Tn</em>}</li>
 *   <li>{@link org.xtext.system.dependency.dependency.Dependency#getTp <em>Tp</em>}</li>
 * </ul>
 *
 * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fn</em>' attribute.
   * @see #setFn(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_Fn()
   * @model
   * @generated
   */
  String getFn();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getFn <em>Fn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fn</em>' attribute.
   * @see #getFn()
   * @generated
   */
  void setFn(String value);

  /**
   * Returns the value of the '<em><b>Fp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fp</em>' attribute.
   * @see #setFp(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_Fp()
   * @model
   * @generated
   */
  String getFp();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getFp <em>Fp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fp</em>' attribute.
   * @see #getFp()
   * @generated
   */
  void setFp(String value);

  /**
   * Returns the value of the '<em><b>O</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>O</em>' attribute.
   * @see #setO(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_O()
   * @model
   * @generated
   */
  String getO();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getO <em>O</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>O</em>' attribute.
   * @see #getO()
   * @generated
   */
  void setO(String value);

  /**
   * Returns the value of the '<em><b>Tn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tn</em>' attribute.
   * @see #setTn(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_Tn()
   * @model
   * @generated
   */
  String getTn();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getTn <em>Tn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tn</em>' attribute.
   * @see #getTn()
   * @generated
   */
  void setTn(String value);

  /**
   * Returns the value of the '<em><b>Tp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tp</em>' attribute.
   * @see #setTp(String)
   * @see org.xtext.system.dependency.dependency.DependencyPackage#getDependency_Tp()
   * @model
   * @generated
   */
  String getTp();

  /**
   * Sets the value of the '{@link org.xtext.system.dependency.dependency.Dependency#getTp <em>Tp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tp</em>' attribute.
   * @see #getTp()
   * @generated
   */
  void setTp(String value);

} // Dependency
