/*
 * generated by Xtext 2.21.0
 */
package org.xtext.base.dependency.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.base.dependency.ui.internal.DependencyActivator;

public class DependencyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DependencyActivator.getInstance().getInjector("org.xtext.base.dependency.Dependency");
	}

}
