/**
 * generated by Xtext 2.21.0
 */
package org.xtext.base.dependency.dependency.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.base.dependency.dependency.BoxLocation;
import org.xtext.base.dependency.dependency.CIM;
import org.xtext.base.dependency.dependency.Dependency;
import org.xtext.base.dependency.dependency.DependencyPackage;
import org.xtext.base.dependency.dependency.GUI;
import org.xtext.base.dependency.dependency.SystemProject;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Project</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getWiki <em>Wiki</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getEnvironment <em>Environment</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getBoxpath <em>Boxpath</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getCims <em>Cims</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getGui <em>Gui</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.impl.SystemProjectImpl#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SystemProjectImpl extends MinimalEObjectImpl.Container implements SystemProject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getWiki() <em>Wiki</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWiki()
   * @generated
   * @ordered
   */
  protected static final String WIKI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWiki() <em>Wiki</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWiki()
   * @generated
   * @ordered
   */
  protected String wiki = WIKI_EDEFAULT;

  /**
   * The default value of the '{@link #getEnvironment() <em>Environment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnvironment()
   * @generated
   * @ordered
   */
  protected static final String ENVIRONMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnvironment() <em>Environment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnvironment()
   * @generated
   * @ordered
   */
  protected String environment = ENVIRONMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getBoxpath() <em>Boxpath</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoxpath()
   * @generated
   * @ordered
   */
  protected static final String BOXPATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBoxpath() <em>Boxpath</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoxpath()
   * @generated
   * @ordered
   */
  protected String boxpath = BOXPATH_EDEFAULT;

  /**
   * The cached value of the '{@link #getCims() <em>Cims</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCims()
   * @generated
   * @ordered
   */
  protected EList<CIM> cims;

  /**
   * The cached value of the '{@link #getDependencies() <em>Dependencies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependencies()
   * @generated
   * @ordered
   */
  protected EList<Dependency> dependencies;

  /**
   * The cached value of the '{@link #getGui() <em>Gui</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGui()
   * @generated
   * @ordered
   */
  protected EList<GUI> gui;

  /**
   * The cached value of the '{@link #getLocation() <em>Location</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocation()
   * @generated
   * @ordered
   */
  protected EList<BoxLocation> location;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DependencyPackage.Literals.SYSTEM_PROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.SYSTEM_PROJECT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWiki()
  {
    return wiki;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWiki(String newWiki)
  {
    String oldWiki = wiki;
    wiki = newWiki;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.SYSTEM_PROJECT__WIKI, oldWiki, wiki));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnvironment()
  {
    return environment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnvironment(String newEnvironment)
  {
    String oldEnvironment = environment;
    environment = newEnvironment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.SYSTEM_PROJECT__ENVIRONMENT, oldEnvironment, environment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBoxpath()
  {
    return boxpath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBoxpath(String newBoxpath)
  {
    String oldBoxpath = boxpath;
    boxpath = newBoxpath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.SYSTEM_PROJECT__BOXPATH, oldBoxpath, boxpath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CIM> getCims()
  {
    if (cims == null)
    {
      cims = new EObjectContainmentEList<CIM>(CIM.class, this, DependencyPackage.SYSTEM_PROJECT__CIMS);
    }
    return cims;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Dependency> getDependencies()
  {
    if (dependencies == null)
    {
      dependencies = new EObjectContainmentEList<Dependency>(Dependency.class, this, DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES);
    }
    return dependencies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GUI> getGui()
  {
    if (gui == null)
    {
      gui = new EObjectContainmentEList<GUI>(GUI.class, this, DependencyPackage.SYSTEM_PROJECT__GUI);
    }
    return gui;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BoxLocation> getLocation()
  {
    if (location == null)
    {
      location = new EObjectContainmentEList<BoxLocation>(BoxLocation.class, this, DependencyPackage.SYSTEM_PROJECT__LOCATION);
    }
    return location;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DependencyPackage.SYSTEM_PROJECT__CIMS:
        return ((InternalEList<?>)getCims()).basicRemove(otherEnd, msgs);
      case DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES:
        return ((InternalEList<?>)getDependencies()).basicRemove(otherEnd, msgs);
      case DependencyPackage.SYSTEM_PROJECT__GUI:
        return ((InternalEList<?>)getGui()).basicRemove(otherEnd, msgs);
      case DependencyPackage.SYSTEM_PROJECT__LOCATION:
        return ((InternalEList<?>)getLocation()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DependencyPackage.SYSTEM_PROJECT__NAME:
        return getName();
      case DependencyPackage.SYSTEM_PROJECT__WIKI:
        return getWiki();
      case DependencyPackage.SYSTEM_PROJECT__ENVIRONMENT:
        return getEnvironment();
      case DependencyPackage.SYSTEM_PROJECT__BOXPATH:
        return getBoxpath();
      case DependencyPackage.SYSTEM_PROJECT__CIMS:
        return getCims();
      case DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES:
        return getDependencies();
      case DependencyPackage.SYSTEM_PROJECT__GUI:
        return getGui();
      case DependencyPackage.SYSTEM_PROJECT__LOCATION:
        return getLocation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DependencyPackage.SYSTEM_PROJECT__NAME:
        setName((String)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__WIKI:
        setWiki((String)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__ENVIRONMENT:
        setEnvironment((String)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__BOXPATH:
        setBoxpath((String)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__CIMS:
        getCims().clear();
        getCims().addAll((Collection<? extends CIM>)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES:
        getDependencies().clear();
        getDependencies().addAll((Collection<? extends Dependency>)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__GUI:
        getGui().clear();
        getGui().addAll((Collection<? extends GUI>)newValue);
        return;
      case DependencyPackage.SYSTEM_PROJECT__LOCATION:
        getLocation().clear();
        getLocation().addAll((Collection<? extends BoxLocation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DependencyPackage.SYSTEM_PROJECT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DependencyPackage.SYSTEM_PROJECT__WIKI:
        setWiki(WIKI_EDEFAULT);
        return;
      case DependencyPackage.SYSTEM_PROJECT__ENVIRONMENT:
        setEnvironment(ENVIRONMENT_EDEFAULT);
        return;
      case DependencyPackage.SYSTEM_PROJECT__BOXPATH:
        setBoxpath(BOXPATH_EDEFAULT);
        return;
      case DependencyPackage.SYSTEM_PROJECT__CIMS:
        getCims().clear();
        return;
      case DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES:
        getDependencies().clear();
        return;
      case DependencyPackage.SYSTEM_PROJECT__GUI:
        getGui().clear();
        return;
      case DependencyPackage.SYSTEM_PROJECT__LOCATION:
        getLocation().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DependencyPackage.SYSTEM_PROJECT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DependencyPackage.SYSTEM_PROJECT__WIKI:
        return WIKI_EDEFAULT == null ? wiki != null : !WIKI_EDEFAULT.equals(wiki);
      case DependencyPackage.SYSTEM_PROJECT__ENVIRONMENT:
        return ENVIRONMENT_EDEFAULT == null ? environment != null : !ENVIRONMENT_EDEFAULT.equals(environment);
      case DependencyPackage.SYSTEM_PROJECT__BOXPATH:
        return BOXPATH_EDEFAULT == null ? boxpath != null : !BOXPATH_EDEFAULT.equals(boxpath);
      case DependencyPackage.SYSTEM_PROJECT__CIMS:
        return cims != null && !cims.isEmpty();
      case DependencyPackage.SYSTEM_PROJECT__DEPENDENCIES:
        return dependencies != null && !dependencies.isEmpty();
      case DependencyPackage.SYSTEM_PROJECT__GUI:
        return gui != null && !gui.isEmpty();
      case DependencyPackage.SYSTEM_PROJECT__LOCATION:
        return location != null && !location.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", wiki: ");
    result.append(wiki);
    result.append(", environment: ");
    result.append(environment);
    result.append(", boxpath: ");
    result.append(boxpath);
    result.append(')');
    return result.toString();
  }

} //SystemProjectImpl
