/**
 * generated by Xtext 2.21.0
 */
package org.xtext.component.dependency.dependency.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.component.dependency.dependency.At;
import org.xtext.component.dependency.dependency.ComponentDependencyObjects;
import org.xtext.component.dependency.dependency.DependencyFactory;
import org.xtext.component.dependency.dependency.DependencyPackage;
import org.xtext.component.dependency.dependency.UserImport;
import org.xtext.component.dependency.dependency.UserName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DependencyPackageImpl extends EPackageImpl implements DependencyPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass componentDependencyObjectsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass userNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass userImportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.component.dependency.dependency.DependencyPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DependencyPackageImpl()
  {
    super(eNS_URI, DependencyFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link DependencyPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DependencyPackage init()
  {
    if (isInited) return (DependencyPackage)EPackage.Registry.INSTANCE.getEPackage(DependencyPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredDependencyPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    DependencyPackageImpl theDependencyPackage = registeredDependencyPackage instanceof DependencyPackageImpl ? (DependencyPackageImpl)registeredDependencyPackage : new DependencyPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theDependencyPackage.createPackageContents();

    // Initialize created meta-data
    theDependencyPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDependencyPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DependencyPackage.eNS_URI, theDependencyPackage);
    return theDependencyPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComponentDependencyObjects()
  {
    return componentDependencyObjectsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponentDependencyObjects_Username()
  {
    return (EReference)componentDependencyObjectsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponentDependencyObjects_Userimport()
  {
    return (EReference)componentDependencyObjectsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponentDependencyObjects_At()
  {
    return (EReference)componentDependencyObjectsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUserName()
  {
    return userNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUserName_Name()
  {
    return (EAttribute)userNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUserImport()
  {
    return userImportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUserImport_Environment()
  {
    return (EAttribute)userImportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUserImport_Boxpath()
  {
    return (EAttribute)userImportEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAt()
  {
    return atEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAt_Name()
  {
    return (EAttribute)atEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DependencyFactory getDependencyFactory()
  {
    return (DependencyFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    componentDependencyObjectsEClass = createEClass(COMPONENT_DEPENDENCY_OBJECTS);
    createEReference(componentDependencyObjectsEClass, COMPONENT_DEPENDENCY_OBJECTS__USERNAME);
    createEReference(componentDependencyObjectsEClass, COMPONENT_DEPENDENCY_OBJECTS__USERIMPORT);
    createEReference(componentDependencyObjectsEClass, COMPONENT_DEPENDENCY_OBJECTS__AT);

    userNameEClass = createEClass(USER_NAME);
    createEAttribute(userNameEClass, USER_NAME__NAME);

    userImportEClass = createEClass(USER_IMPORT);
    createEAttribute(userImportEClass, USER_IMPORT__ENVIRONMENT);
    createEAttribute(userImportEClass, USER_IMPORT__BOXPATH);

    atEClass = createEClass(AT);
    createEAttribute(atEClass, AT__NAME);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(componentDependencyObjectsEClass, ComponentDependencyObjects.class, "ComponentDependencyObjects", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComponentDependencyObjects_Username(), this.getUserName(), null, "username", null, 0, 1, ComponentDependencyObjects.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponentDependencyObjects_Userimport(), this.getUserImport(), null, "userimport", null, 0, 1, ComponentDependencyObjects.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponentDependencyObjects_At(), this.getAt(), null, "at", null, 0, 1, ComponentDependencyObjects.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(userNameEClass, UserName.class, "UserName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUserName_Name(), ecorePackage.getEString(), "name", null, 0, 1, UserName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(userImportEClass, UserImport.class, "UserImport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUserImport_Environment(), ecorePackage.getEString(), "environment", null, 0, 1, UserImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUserImport_Boxpath(), ecorePackage.getEString(), "boxpath", null, 0, 1, UserImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atEClass, At.class, "At", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAt_Name(), ecorePackage.getEString(), "name", null, 0, 1, At.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //DependencyPackageImpl
