//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentB.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentBAcePortFactory.hh"


// initialize static singleton pointer to zero
ComponentB* ComponentB::_componentB = 0;

// constructor
ComponentB::ComponentB()
{
	std::cout << "constructor of ComponentB\n";
	
	// set all pointer members to NULL
	activity1 = NULL;
	activity1Trigger = NULL;
	b_In = NULL;
	b_InInputTaskTrigger = NULL;
	b_InUpcallManager = NULL;
	b_Out = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentB";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.b_Out.serviceName = "B_Out";
	connections.b_Out.roboticMiddleware = "ACE_SmartSoft";
	connections.b_In.wiringName = "B_In";
	connections.b_In.serverName = "unknown";
	connections.b_In.serviceName = "unknown";
	connections.b_In.interval = 1;
	connections.b_In.roboticMiddleware = "ACE_SmartSoft";
	connections.activity1.minActFreq = 0.0;
	connections.activity1.maxActFreq = 0.0;
	// scheduling default parameters
	connections.activity1.scheduler = "DEFAULT";
	connections.activity1.priority = -1;
	connections.activity1.cpuAffinity = -1;
	
	// initialize members of PlainOpcUaComponentBExtension
	
}

void ComponentB::addPortFactory(const std::string &name, ComponentBPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentB::addExtension(ComponentBExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentB::getComponentImpl()
{
	return dynamic_cast<ComponentBAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentB::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode ComponentB::connectB_In(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = b_In->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->b_In->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	b_In->subscribe(connections.b_In.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentB::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectB_In(connections.b_In.serverName, connections.b_In.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentB::startAllTasks() {
	// start task Activity1
	if(connections.activity1.scheduler != "DEFAULT") {
		ACE_Sched_Params activity1_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.activity1.scheduler == "FIFO") {
			activity1_SchedParams.policy(ACE_SCHED_FIFO);
			activity1_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.activity1.scheduler == "RR") {
			activity1_SchedParams.policy(ACE_SCHED_RR);
			activity1_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		activity1->start(activity1_SchedParams, connections.activity1.cpuAffinity);
	} else {
		activity1->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentB::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentB::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "B_In") return b_InInputTaskTrigger;
	
	return NULL;
}


void ComponentB::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of PlainOpcUaComponentBExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentBPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentBAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentB is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		b_Out = portFactoryRegistry[connections.b_Out.roboticMiddleware]->createB_Out(connections.b_Out.serviceName);
		
		// create client ports
		b_In = portFactoryRegistry[connections.b_In.roboticMiddleware]->createB_In();
		
		// create InputTaskTriggers and UpcallManagers
		b_InInputTaskTrigger = new Smart::InputTaskTrigger<CommBasicObjects::CommBaseState>(b_In);
		b_InUpcallManager = new B_InUpcallManager(b_In);
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.b_In.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<CommBasicObjects::CommBaseState>*>(b_In)->add(wiringSlave, connections.b_In.wiringName);
		}
		
		
		
		// create Task Activity1
		activity1 = new Activity1(component);
		// configure input-links
		b_InUpcallManager->attach(activity1);
		// configure task-trigger (if task is configurable)
		if(connections.activity1.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.activity1.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(activity1);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				activity1Trigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Activity1" << std::endl;
			}
		} else if(connections.activity1.trigger == "DataTriggered") {
			activity1Trigger = getInputTaskTriggerFromString(connections.activity1.inPortRef);
			if(activity1Trigger != NULL) {
				activity1Trigger->attach(activity1, connections.activity1.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.activity1.inPortRef << " as activation source for Task Activity1" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentB::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentB::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	b_InUpcallManager->detach(activity1);
	// unlink the TaskTrigger
	if(activity1Trigger != NULL){
		activity1Trigger->detach(activity1);
		delete activity1;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete b_InInputTaskTrigger;
	delete b_InUpcallManager;

	// destroy client ports
	delete b_In;

	// destroy server ports
	delete b_Out;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of PlainOpcUaComponentBExtension
	
}

void ComponentB::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentB.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentB.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentB.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client B_In
		parameter.getString("B_In", "serviceName", connections.b_In.serviceName);
		parameter.getString("B_In", "serverName", connections.b_In.serverName);
		parameter.getString("B_In", "wiringName", connections.b_In.wiringName);
		parameter.getInteger("B_In", "interval", connections.b_In.interval);
		if(parameter.checkIfParameterExists("B_In", "roboticMiddleware")) {
			parameter.getString("B_In", "roboticMiddleware", connections.b_In.roboticMiddleware);
		}
		
		// load parameters for server B_Out
		parameter.getString("B_Out", "serviceName", connections.b_Out.serviceName);
		if(parameter.checkIfParameterExists("B_Out", "roboticMiddleware")) {
			parameter.getString("B_Out", "roboticMiddleware", connections.b_Out.roboticMiddleware);
		}
		
		// load parameters for task Activity1
		parameter.getDouble("Activity1", "minActFreqHz", connections.activity1.minActFreq);
		parameter.getDouble("Activity1", "maxActFreqHz", connections.activity1.maxActFreq);
		parameter.getString("Activity1", "triggerType", connections.activity1.trigger);
		if(connections.activity1.trigger == "PeriodicTimer") {
			parameter.getDouble("Activity1", "periodicActFreqHz", connections.activity1.periodicActFreq);
		} else if(connections.activity1.trigger == "DataTriggered") {
			parameter.getString("Activity1", "inPortRef", connections.activity1.inPortRef);
			parameter.getInteger("Activity1", "prescale", connections.activity1.prescale);
		}
		if(parameter.checkIfParameterExists("Activity1", "scheduler")) {
			parameter.getString("Activity1", "scheduler", connections.activity1.scheduler);
		}
		if(parameter.checkIfParameterExists("Activity1", "priority")) {
			parameter.getInteger("Activity1", "priority", connections.activity1.priority);
		}
		if(parameter.checkIfParameterExists("Activity1", "cpuAffinity")) {
			parameter.getInteger("Activity1", "cpuAffinity", connections.activity1.cpuAffinity);
		}
		
		// load parameters for PlainOpcUaComponentBExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
