/*
 * generated by Xtext 2.23.0
 */
package org.xtext.base.dependency.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDependencyScopeProvider extends DelegatingScopeProvider {
}
