/*
 * generated by Xtext 2.21.0
 */
package org.xtext.system.dependency.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDependencyScopeProvider extends DelegatingScopeProvider {
}
