/**
 * generated by Xtext 2.21.0
 */
package org.xtext.component.dependency.dependency;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.component.dependency.dependency.DependencyFactory
 * @model kind="package"
 * @generated
 */
public interface DependencyPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dependency";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/component/dependency/Dependency";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dependency";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DependencyPackage eINSTANCE = org.xtext.component.dependency.dependency.impl.DependencyPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.component.dependency.dependency.impl.ComponentDependencyObjectsImpl <em>Component Dependency Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.component.dependency.dependency.impl.ComponentDependencyObjectsImpl
   * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getComponentDependencyObjects()
   * @generated
   */
  int COMPONENT_DEPENDENCY_OBJECTS = 0;

  /**
   * The feature id for the '<em><b>Username</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DEPENDENCY_OBJECTS__USERNAME = 0;

  /**
   * The feature id for the '<em><b>Userimport</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DEPENDENCY_OBJECTS__USERIMPORT = 1;

  /**
   * The feature id for the '<em><b>At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DEPENDENCY_OBJECTS__AT = 2;

  /**
   * The number of structural features of the '<em>Component Dependency Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DEPENDENCY_OBJECTS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.component.dependency.dependency.impl.UserNameImpl <em>User Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.component.dependency.dependency.impl.UserNameImpl
   * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getUserName()
   * @generated
   */
  int USER_NAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>User Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.component.dependency.dependency.impl.UserImportImpl <em>User Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.component.dependency.dependency.impl.UserImportImpl
   * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getUserImport()
   * @generated
   */
  int USER_IMPORT = 2;

  /**
   * The feature id for the '<em><b>Environment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT__ENVIRONMENT = 0;

  /**
   * The feature id for the '<em><b>Boxpath</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT__BOXPATH = 1;

  /**
   * The number of structural features of the '<em>User Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_IMPORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.component.dependency.dependency.impl.AtImpl <em>At</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.component.dependency.dependency.impl.AtImpl
   * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getAt()
   * @generated
   */
  int AT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT__NAME = 0;

  /**
   * The number of structural features of the '<em>At</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.component.dependency.dependency.ComponentDependencyObjects <em>Component Dependency Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Dependency Objects</em>'.
   * @see org.xtext.component.dependency.dependency.ComponentDependencyObjects
   * @generated
   */
  EClass getComponentDependencyObjects();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.component.dependency.dependency.ComponentDependencyObjects#getUsername <em>Username</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Username</em>'.
   * @see org.xtext.component.dependency.dependency.ComponentDependencyObjects#getUsername()
   * @see #getComponentDependencyObjects()
   * @generated
   */
  EReference getComponentDependencyObjects_Username();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.component.dependency.dependency.ComponentDependencyObjects#getUserimport <em>Userimport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Userimport</em>'.
   * @see org.xtext.component.dependency.dependency.ComponentDependencyObjects#getUserimport()
   * @see #getComponentDependencyObjects()
   * @generated
   */
  EReference getComponentDependencyObjects_Userimport();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.component.dependency.dependency.ComponentDependencyObjects#getAt <em>At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>At</em>'.
   * @see org.xtext.component.dependency.dependency.ComponentDependencyObjects#getAt()
   * @see #getComponentDependencyObjects()
   * @generated
   */
  EReference getComponentDependencyObjects_At();

  /**
   * Returns the meta object for class '{@link org.xtext.component.dependency.dependency.UserName <em>User Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Name</em>'.
   * @see org.xtext.component.dependency.dependency.UserName
   * @generated
   */
  EClass getUserName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.component.dependency.dependency.UserName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.component.dependency.dependency.UserName#getName()
   * @see #getUserName()
   * @generated
   */
  EAttribute getUserName_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.component.dependency.dependency.UserImport <em>User Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Import</em>'.
   * @see org.xtext.component.dependency.dependency.UserImport
   * @generated
   */
  EClass getUserImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.component.dependency.dependency.UserImport#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Environment</em>'.
   * @see org.xtext.component.dependency.dependency.UserImport#getEnvironment()
   * @see #getUserImport()
   * @generated
   */
  EAttribute getUserImport_Environment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.component.dependency.dependency.UserImport#getBoxpath <em>Boxpath</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boxpath</em>'.
   * @see org.xtext.component.dependency.dependency.UserImport#getBoxpath()
   * @see #getUserImport()
   * @generated
   */
  EAttribute getUserImport_Boxpath();

  /**
   * Returns the meta object for class '{@link org.xtext.component.dependency.dependency.At <em>At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>At</em>'.
   * @see org.xtext.component.dependency.dependency.At
   * @generated
   */
  EClass getAt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.component.dependency.dependency.At#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.component.dependency.dependency.At#getName()
   * @see #getAt()
   * @generated
   */
  EAttribute getAt_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DependencyFactory getDependencyFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.component.dependency.dependency.impl.ComponentDependencyObjectsImpl <em>Component Dependency Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.component.dependency.dependency.impl.ComponentDependencyObjectsImpl
     * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getComponentDependencyObjects()
     * @generated
     */
    EClass COMPONENT_DEPENDENCY_OBJECTS = eINSTANCE.getComponentDependencyObjects();

    /**
     * The meta object literal for the '<em><b>Username</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DEPENDENCY_OBJECTS__USERNAME = eINSTANCE.getComponentDependencyObjects_Username();

    /**
     * The meta object literal for the '<em><b>Userimport</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DEPENDENCY_OBJECTS__USERIMPORT = eINSTANCE.getComponentDependencyObjects_Userimport();

    /**
     * The meta object literal for the '<em><b>At</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DEPENDENCY_OBJECTS__AT = eINSTANCE.getComponentDependencyObjects_At();

    /**
     * The meta object literal for the '{@link org.xtext.component.dependency.dependency.impl.UserNameImpl <em>User Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.component.dependency.dependency.impl.UserNameImpl
     * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getUserName()
     * @generated
     */
    EClass USER_NAME = eINSTANCE.getUserName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_NAME__NAME = eINSTANCE.getUserName_Name();

    /**
     * The meta object literal for the '{@link org.xtext.component.dependency.dependency.impl.UserImportImpl <em>User Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.component.dependency.dependency.impl.UserImportImpl
     * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getUserImport()
     * @generated
     */
    EClass USER_IMPORT = eINSTANCE.getUserImport();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_IMPORT__ENVIRONMENT = eINSTANCE.getUserImport_Environment();

    /**
     * The meta object literal for the '<em><b>Boxpath</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_IMPORT__BOXPATH = eINSTANCE.getUserImport_Boxpath();

    /**
     * The meta object literal for the '{@link org.xtext.component.dependency.dependency.impl.AtImpl <em>At</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.component.dependency.dependency.impl.AtImpl
     * @see org.xtext.component.dependency.dependency.impl.DependencyPackageImpl#getAt()
     * @generated
     */
    EClass AT = eINSTANCE.getAt();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AT__NAME = eINSTANCE.getAt_Name();

  }

} //DependencyPackage
