/*
 * generated by Xtext 2.21.0
 */
package org.xtext.system.dependency.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DependencyGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SystemDependencyObjectsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.SystemDependencyObjects");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cUsernameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cUsernameUserNameParserRuleCall_0_0 = (RuleCall)cUsernameAssignment_0.eContents().get(0);
		private final Assignment cUserimportAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUserimportUserImportParserRuleCall_1_0 = (RuleCall)cUserimportAssignment_1.eContents().get(0);
		private final Assignment cAtAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAtAtParserRuleCall_2_0 = (RuleCall)cAtAssignment_2.eContents().get(0);
		private final Assignment cDependenciesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDependenciesDependencyParserRuleCall_3_0 = (RuleCall)cDependenciesAssignment_3.eContents().get(0);
		private final Assignment cGuisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGuisGUIParserRuleCall_4_0 = (RuleCall)cGuisAssignment_4.eContents().get(0);
		
		//SystemDependencyObjects:
		//	username=UserName
		//	userimport=UserImport
		//	at=At
		//	dependencies+=Dependency*
		//	guis+=GUI*;
		@Override public ParserRule getRule() { return rule; }
		
		//username=UserName userimport=UserImport at=At dependencies+=Dependency* guis+=GUI*
		public Group getGroup() { return cGroup; }
		
		//username=UserName
		public Assignment getUsernameAssignment_0() { return cUsernameAssignment_0; }
		
		//UserName
		public RuleCall getUsernameUserNameParserRuleCall_0_0() { return cUsernameUserNameParserRuleCall_0_0; }
		
		//userimport=UserImport
		public Assignment getUserimportAssignment_1() { return cUserimportAssignment_1; }
		
		//UserImport
		public RuleCall getUserimportUserImportParserRuleCall_1_0() { return cUserimportUserImportParserRuleCall_1_0; }
		
		//at=At
		public Assignment getAtAssignment_2() { return cAtAssignment_2; }
		
		//At
		public RuleCall getAtAtParserRuleCall_2_0() { return cAtAtParserRuleCall_2_0; }
		
		//dependencies+=Dependency*
		public Assignment getDependenciesAssignment_3() { return cDependenciesAssignment_3; }
		
		//Dependency
		public RuleCall getDependenciesDependencyParserRuleCall_3_0() { return cDependenciesDependencyParserRuleCall_3_0; }
		
		//guis+=GUI*
		public Assignment getGuisAssignment_4() { return cGuisAssignment_4; }
		
		//GUI
		public RuleCall getGuisGUIParserRuleCall_4_0() { return cGuisGUIParserRuleCall_4_0; }
	}
	public class UserNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.UserName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//UserName:
		//	'UserName' ':' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'UserName' ':' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'UserName'
		public Keyword getUserNameKeyword_0() { return cUserNameKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
	}
	public class UserImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.UserImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEnvironmentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEnvironmentSTRINGTerminalRuleCall_1_0 = (RuleCall)cEnvironmentAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBoxpathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBoxpathSTRINGTerminalRuleCall_3_0 = (RuleCall)cBoxpathAssignment_3.eContents().get(0);
		
		//UserImport:
		//	'import' environment=STRING 'from' boxpath=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' environment=STRING 'from' boxpath=STRING
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//environment=STRING
		public Assignment getEnvironmentAssignment_1() { return cEnvironmentAssignment_1; }
		
		//STRING
		public RuleCall getEnvironmentSTRINGTerminalRuleCall_1_0() { return cEnvironmentSTRINGTerminalRuleCall_1_0; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//boxpath=STRING
		public Assignment getBoxpathAssignment_3() { return cBoxpathAssignment_3; }
		
		//STRING
		public RuleCall getBoxpathSTRINGTerminalRuleCall_3_0() { return cBoxpathSTRINGTerminalRuleCall_3_0; }
	}
	public class AtElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.At");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSaveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCommercialAtKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//At:
		//	'Save' '@' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Save' '@' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'Save'
		public Keyword getSaveKeyword_0() { return cSaveKeyword_0; }
		
		//'@'
		public Keyword getCommercialAtKeyword_1() { return cCommercialAtKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
	}
	public class DependencyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.Dependency");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDependencyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cFnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFnSTRINGTerminalRuleCall_2_0 = (RuleCall)cFnAssignment_2.eContents().get(0);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFpAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFpSTRINGTerminalRuleCall_4_0 = (RuleCall)cFpAssignment_4.eContents().get(0);
		private final Keyword cHyphenMinusHyphenMinusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOSTRINGTerminalRuleCall_6_0 = (RuleCall)cOAssignment_6.eContents().get(0);
		private final Keyword cHyphenMinusHyphenMinusGreaterThanSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTnAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTnSTRINGTerminalRuleCall_8_0 = (RuleCall)cTnAssignment_8.eContents().get(0);
		private final Keyword cFullStopKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTpAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTpSTRINGTerminalRuleCall_10_0 = (RuleCall)cTpAssignment_10.eContents().get(0);
		
		//Dependency:
		//	'Dependency' name=STRING
		//	fn=STRING '.' fp=STRING
		//	'--' o=STRING '-->'
		//	tn=STRING '.' tp=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Dependency' name=STRING fn=STRING '.' fp=STRING '--' o=STRING '-->' tn=STRING '.' tp=STRING
		public Group getGroup() { return cGroup; }
		
		//'Dependency'
		public Keyword getDependencyKeyword_0() { return cDependencyKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//fn=STRING
		public Assignment getFnAssignment_2() { return cFnAssignment_2; }
		
		//STRING
		public RuleCall getFnSTRINGTerminalRuleCall_2_0() { return cFnSTRINGTerminalRuleCall_2_0; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//fp=STRING
		public Assignment getFpAssignment_4() { return cFpAssignment_4; }
		
		//STRING
		public RuleCall getFpSTRINGTerminalRuleCall_4_0() { return cFpSTRINGTerminalRuleCall_4_0; }
		
		//'--'
		public Keyword getHyphenMinusHyphenMinusKeyword_5() { return cHyphenMinusHyphenMinusKeyword_5; }
		
		//o=STRING
		public Assignment getOAssignment_6() { return cOAssignment_6; }
		
		//STRING
		public RuleCall getOSTRINGTerminalRuleCall_6_0() { return cOSTRINGTerminalRuleCall_6_0; }
		
		//'-->'
		public Keyword getHyphenMinusHyphenMinusGreaterThanSignKeyword_7() { return cHyphenMinusHyphenMinusGreaterThanSignKeyword_7; }
		
		//tn=STRING
		public Assignment getTnAssignment_8() { return cTnAssignment_8; }
		
		//STRING
		public RuleCall getTnSTRINGTerminalRuleCall_8_0() { return cTnSTRINGTerminalRuleCall_8_0; }
		
		//'.'
		public Keyword getFullStopKeyword_9() { return cFullStopKeyword_9; }
		
		//tp=STRING
		public Assignment getTpAssignment_10() { return cTpAssignment_10; }
		
		//STRING
		public RuleCall getTpSTRINGTerminalRuleCall_10_0() { return cTpSTRINGTerminalRuleCall_10_0; }
	}
	public class GUIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.system.dependency.Dependency.GUI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGUIKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXINTTerminalRuleCall_3_0 = (RuleCall)cXAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cYAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cYINTTerminalRuleCall_5_0 = (RuleCall)cYAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GUI:
		//	'GUI' name=STRING '(' x=INT ',' y=INT ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'GUI' name=STRING '(' x=INT ',' y=INT ')'
		public Group getGroup() { return cGroup; }
		
		//'GUI'
		public Keyword getGUIKeyword_0() { return cGUIKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//x=INT
		public Assignment getXAssignment_3() { return cXAssignment_3; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_3_0() { return cXINTTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//y=INT
		public Assignment getYAssignment_5() { return cYAssignment_5; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_5_0() { return cYINTTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	
	
	private final SystemDependencyObjectsElements pSystemDependencyObjects;
	private final UserNameElements pUserName;
	private final UserImportElements pUserImport;
	private final AtElements pAt;
	private final DependencyElements pDependency;
	private final GUIElements pGUI;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DependencyGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystemDependencyObjects = new SystemDependencyObjectsElements();
		this.pUserName = new UserNameElements();
		this.pUserImport = new UserImportElements();
		this.pAt = new AtElements();
		this.pDependency = new DependencyElements();
		this.pGUI = new GUIElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.system.dependency.Dependency".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SystemDependencyObjects:
	//	username=UserName
	//	userimport=UserImport
	//	at=At
	//	dependencies+=Dependency*
	//	guis+=GUI*;
	public SystemDependencyObjectsElements getSystemDependencyObjectsAccess() {
		return pSystemDependencyObjects;
	}
	
	public ParserRule getSystemDependencyObjectsRule() {
		return getSystemDependencyObjectsAccess().getRule();
	}
	
	//UserName:
	//	'UserName' ':' name=STRING;
	public UserNameElements getUserNameAccess() {
		return pUserName;
	}
	
	public ParserRule getUserNameRule() {
		return getUserNameAccess().getRule();
	}
	
	//UserImport:
	//	'import' environment=STRING 'from' boxpath=STRING;
	public UserImportElements getUserImportAccess() {
		return pUserImport;
	}
	
	public ParserRule getUserImportRule() {
		return getUserImportAccess().getRule();
	}
	
	//At:
	//	'Save' '@' name=STRING;
	public AtElements getAtAccess() {
		return pAt;
	}
	
	public ParserRule getAtRule() {
		return getAtAccess().getRule();
	}
	
	//Dependency:
	//	'Dependency' name=STRING
	//	fn=STRING '.' fp=STRING
	//	'--' o=STRING '-->'
	//	tn=STRING '.' tp=STRING;
	public DependencyElements getDependencyAccess() {
		return pDependency;
	}
	
	public ParserRule getDependencyRule() {
		return getDependencyAccess().getRule();
	}
	
	//GUI:
	//	'GUI' name=STRING '(' x=INT ',' y=INT ')';
	public GUIElements getGUIAccess() {
		return pGUI;
	}
	
	public ParserRule getGUIRule() {
		return getGUIAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
