/*
 * generated by Xtext 2.23.0
 */
package org.xtext.base.dependency.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.base.dependency.parser.antlr.internal.InternalDependencyParser;
import org.xtext.base.dependency.services.DependencyGrammarAccess;

public class DependencyParser extends AbstractAntlrParser {

	@Inject
	private DependencyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDependencyParser createParser(XtextTokenStream stream) {
		return new InternalDependencyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DependencyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DependencyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
