/*
 * generated by Xtext 2.21.0
 */
package org.xtext.base.dependency.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DependencyAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/base/dependency/parser/antlr/internal/InternalDependency.tokens");
	}
}
