/*
 * generated by Xtext 2.21.0
 */
package org.xtext.system.dependency.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.system.dependency.ide.contentassist.antlr.internal.InternalDependencyParser;
import org.xtext.system.dependency.services.DependencyGrammarAccess;

public class DependencyParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DependencyGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DependencyGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getGroup(), "rule__SystemDependencyObjects__Group__0");
			builder.put(grammarAccess.getUserNameAccess().getGroup(), "rule__UserName__Group__0");
			builder.put(grammarAccess.getUserImportAccess().getGroup(), "rule__UserImport__Group__0");
			builder.put(grammarAccess.getAtAccess().getGroup(), "rule__At__Group__0");
			builder.put(grammarAccess.getDependencyAccess().getGroup(), "rule__Dependency__Group__0");
			builder.put(grammarAccess.getGUIAccess().getGroup(), "rule__GUI__Group__0");
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getUsernameAssignment_0(), "rule__SystemDependencyObjects__UsernameAssignment_0");
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getUserimportAssignment_1(), "rule__SystemDependencyObjects__UserimportAssignment_1");
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getAtAssignment_2(), "rule__SystemDependencyObjects__AtAssignment_2");
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getDependenciesAssignment_3(), "rule__SystemDependencyObjects__DependenciesAssignment_3");
			builder.put(grammarAccess.getSystemDependencyObjectsAccess().getGuisAssignment_4(), "rule__SystemDependencyObjects__GuisAssignment_4");
			builder.put(grammarAccess.getUserNameAccess().getNameAssignment_2(), "rule__UserName__NameAssignment_2");
			builder.put(grammarAccess.getUserImportAccess().getEnvironmentAssignment_1(), "rule__UserImport__EnvironmentAssignment_1");
			builder.put(grammarAccess.getUserImportAccess().getBoxpathAssignment_3(), "rule__UserImport__BoxpathAssignment_3");
			builder.put(grammarAccess.getAtAccess().getNameAssignment_2(), "rule__At__NameAssignment_2");
			builder.put(grammarAccess.getDependencyAccess().getNameAssignment_1(), "rule__Dependency__NameAssignment_1");
			builder.put(grammarAccess.getDependencyAccess().getFnAssignment_2(), "rule__Dependency__FnAssignment_2");
			builder.put(grammarAccess.getDependencyAccess().getFpAssignment_4(), "rule__Dependency__FpAssignment_4");
			builder.put(grammarAccess.getDependencyAccess().getOAssignment_6(), "rule__Dependency__OAssignment_6");
			builder.put(grammarAccess.getDependencyAccess().getTnAssignment_8(), "rule__Dependency__TnAssignment_8");
			builder.put(grammarAccess.getDependencyAccess().getTpAssignment_10(), "rule__Dependency__TpAssignment_10");
			builder.put(grammarAccess.getGUIAccess().getNameAssignment_1(), "rule__GUI__NameAssignment_1");
			builder.put(grammarAccess.getGUIAccess().getXAssignment_3(), "rule__GUI__XAssignment_3");
			builder.put(grammarAccess.getGUIAccess().getYAssignment_5(), "rule__GUI__YAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DependencyGrammarAccess grammarAccess;

	@Override
	protected InternalDependencyParser createParser() {
		InternalDependencyParser result = new InternalDependencyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DependencyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DependencyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
