/**
 * generated by Xtext 2.23.0
 */
package org.xtext.base.dependency.dependency;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getWiki <em>Wiki</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getObjects <em>Objects</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getComponents <em>Components</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getConnectors <em>Connectors</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.Environment#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment()
 * @model
 * @generated
 */
public interface Environment extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.Environment#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Wiki</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wiki</em>' attribute.
   * @see #setWiki(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Wiki()
   * @model
   * @generated
   */
  String getWiki();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.Environment#getWiki <em>Wiki</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wiki</em>' attribute.
   * @see #getWiki()
   * @generated
   */
  void setWiki(String value);

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.DependencyObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Objects()
   * @model containment="true"
   * @generated
   */
  EList<DependencyObject> getObjects();

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.DependencyComponent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Components()
   * @model containment="true"
   * @generated
   */
  EList<DependencyComponent> getComponents();

  /**
   * Returns the value of the '<em><b>Connectors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.DependencyConnectors}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connectors</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Connectors()
   * @model containment="true"
   * @generated
   */
  EList<DependencyConnectors> getConnectors();

  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.At}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getEnvironment_Location()
   * @model containment="true"
   * @generated
   */
  EList<At> getLocation();

} // Environment
