/**
 * generated by Xtext 2.21.0
 */
package org.xtext.base.dependency.dependency;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GUI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.base.dependency.dependency.GUI#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.GUI#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.GUI#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.GUI#getWiki <em>Wiki</em>}</li>
 * </ul>
 *
 * @see org.xtext.base.dependency.dependency.DependencyPackage#getGUI()
 * @model
 * @generated
 */
public interface GUI extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getGUI_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.GUI#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getGUI_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.GUI#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getGUI_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.GUI#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Wiki</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wiki</em>' attribute.
   * @see #setWiki(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getGUI_Wiki()
   * @model
   * @generated
   */
  String getWiki();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.GUI#getWiki <em>Wiki</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wiki</em>' attribute.
   * @see #getWiki()
   * @generated
   */
  void setWiki(String value);

} // GUI
