/**
 * generated by Xtext 2.21.0
 */
package org.xtext.base.dependency.dependency;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getWiki <em>Wiki</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getEnvironment <em>Environment</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getBoxpath <em>Boxpath</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getCims <em>Cims</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getGui <em>Gui</em>}</li>
 *   <li>{@link org.xtext.base.dependency.dependency.SystemProject#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject()
 * @model
 * @generated
 */
public interface SystemProject extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.SystemProject#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Wiki</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wiki</em>' attribute.
   * @see #setWiki(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Wiki()
   * @model
   * @generated
   */
  String getWiki();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.SystemProject#getWiki <em>Wiki</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wiki</em>' attribute.
   * @see #getWiki()
   * @generated
   */
  void setWiki(String value);

  /**
   * Returns the value of the '<em><b>Environment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment</em>' attribute.
   * @see #setEnvironment(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Environment()
   * @model
   * @generated
   */
  String getEnvironment();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.SystemProject#getEnvironment <em>Environment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Environment</em>' attribute.
   * @see #getEnvironment()
   * @generated
   */
  void setEnvironment(String value);

  /**
   * Returns the value of the '<em><b>Boxpath</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boxpath</em>' attribute.
   * @see #setBoxpath(String)
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Boxpath()
   * @model
   * @generated
   */
  String getBoxpath();

  /**
   * Sets the value of the '{@link org.xtext.base.dependency.dependency.SystemProject#getBoxpath <em>Boxpath</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boxpath</em>' attribute.
   * @see #getBoxpath()
   * @generated
   */
  void setBoxpath(String value);

  /**
   * Returns the value of the '<em><b>Cims</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.CIM}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cims</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Cims()
   * @model containment="true"
   * @generated
   */
  EList<CIM> getCims();

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.Dependency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Dependencies()
   * @model containment="true"
   * @generated
   */
  EList<Dependency> getDependencies();

  /**
   * Returns the value of the '<em><b>Gui</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.GUI}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gui</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Gui()
   * @model containment="true"
   * @generated
   */
  EList<GUI> getGui();

  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.base.dependency.dependency.BoxLocation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference list.
   * @see org.xtext.base.dependency.dependency.DependencyPackage#getSystemProject_Location()
   * @model containment="true"
   * @generated
   */
  EList<BoxLocation> getLocation();

} // SystemProject
