//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DGSERVICE_DGBASICCOMMOBJECT_ACE_H_
#define DGSERVICE_DGBASICCOMMOBJECT_ACE_H_

#include "DGService/DGBasicCommObject.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure DGBasicCommObject
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DGServiceIDL::DGBasicCommObject &data);

// de-serialization operator for DataStructure DGBasicCommObject
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DGServiceIDL::DGBasicCommObject &data);

// serialization operator for CommunicationObject DGBasicCommObject
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DGService::DGBasicCommObject &obj);

// de-serialization operator for CommunicationObject DGBasicCommObject
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DGService::DGBasicCommObject &obj);

#endif /* DGSERVICE_DGBASICCOMMOBJECT_ACE_H_ */
