//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _A_IN_UPCALL_MANAGER_HH
#define _A_IN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "A_InUpcallInterface.hh"

/** A_InUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort A_In and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class A_InUpcallManager
:	public Smart::IInputHandler<CommBasicObjects::CommBaseState>
{
private:
	// list of associated updalls
	std::list<A_InUpcallInterface*> upcalls;

	// call the on_A_In of all the attached A_InUpcallInterfaces
	void notify_upcalls(const CommBasicObjects::CommBaseState &input);
	
protected:
	virtual void handle_input(const CommBasicObjects::CommBaseState &input) {
		// relay input-handling to all attached A_InUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	A_InUpcallManager(
		Smart::InputSubject<CommBasicObjects::CommBaseState> *subject,
		const int &prescaleFactor=1
	);
	virtual ~A_InUpcallManager();
	
	void attach(A_InUpcallInterface *upcall);
	void detach(A_InUpcallInterface *upcall);
};

#endif
